### ISSUE TITLE
update terraform-provider-okta to use the newly refactored policies struct from the Articulate Okta SDK

### ISSUE THREAD

**Issue by PurrBiscuit** [articulate/terraform-provider-okta#65]
the articulate/oktasdk-go package was [updated last week](https://github.com/articulate/oktasdk-go/pull/27) to refactor some of the structs in the policies.go file which has made it incompatible with how the `okta_policies` resource (should be renamed to `okta_policy` as well) is constructing/populating them.  We end up with errors in the terraform integration tests now around that which look like:

```
=== RUN   TestAccOktaPolicies_nameErrors
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17b24f3]

goroutine 1608 [running]:
github.com/articulate/terraform-provider-okta/okta.policySignOn(0x19c69b8, 0x6, 0xc4205f3570, 0x18a3b80, 0xc4204045c0, 0x0, 0x0)
	/Users/spurr/golang/src/github.com/articulate/terraform-provider-okta/okta/resource_policies.go:593 +0x2e3
github.com/articulate/terraform-provider-okta/okta.resourcePolicyCreate(0xc4205f3570, 0x18a3b80, 0xc4204045c0, 0x24, 0x1fc4b40)
	/Users/spurr/golang/src/github.com/articulate/terraform-provider-okta/okta/resource_policies.go:290 +0x674
github.com/articulate/terraform-provider-okta/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4203019d0, 0xc4200e3c20, 0xc42049c0c0, 0x18a3b80, 0xc4204045c0, 0xc4200de801, 0x46, 0x0)
```

We should refactor this in the `okta_policy` resource to match the struct from the articulate/oktasdk-go package.

**Comment by PurrBiscuit** [comment]
steps to reproduce:

1. run `dep ensure -update` to update our `articulate/okta` package to the latest - it's currently locked to the last working version via Gopkg.lock.
2. run `TF_ACC=1 go test -v` from the `okta` directory in this repo.
3. see the panic error.

side note - you can also use delve to help debug by running `TF_ACC=1 dlv test -- -test.v`
